##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator
##########

# URL AYARLARI
url: "https://hacyolundabirkarinca.github.io"
baseurl: "/koleksiyonum"
source-code: "https://github.com/HacYolundaBirKarinca/koleksiyonum"
lang: tr

# SITE AYARLARI
title: "Hac Yolunda Bir Karınca: Mehmet Genç"
tagline: "Dijital Biyografi"
description: "Mehmet Genç'in dijital biyografisini oluşturan kronolojik veriyi ihtiva eder."
author: "MehmetGencGonulluleri"

# KOLEKSIYON AYARLARI
# _data klasöründeki dosyanızın adı collection_metadata.csv olmalı!
metadata: collection_metadata

# TEKNİK AYARLAR (Bunlara dokunmayın)
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed

# Konu bulutunda görünmesi istenmeyen kelimeler
subject_stopwords: "MGenc Gonullusu"
